sudo: required
language : cpp
os:
  - linux
  - osx
compiler:
  - gcc
script:
  - autoreconf && ./configure && automake && make && make check

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install 'requests[security]'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user cpp-coveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  brew update               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  eval "$(pyenv init -)"    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  pyenv install 2.7.6       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  pyenv global 2.7.6        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  pyenv rehash              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  pip install cpp-coveralls ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  pyenv rehash              ; fi

after_success:
  - coveralls --dryrun --gcov-options '\-lp'