language: cpp
compiler:
  - gcc
  - clang
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode8.2
      sudo: false
script:
  - autoreconf && ./configure && automake && make && make check

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user cpp-coveralls; fi

after_success:
  -  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; if [[ "$CC" == "gcc" ]]; then coveralls --gcov-options '\-lp'; fi; fi