codecov:
  disable_default_path_fixes: true


coverage:
  precision: 0
  range:
  - 60.0
  - 80.0
  round: down
  status:
    changes: false
    default_rules:
      flag_coverage_not_uploaded_behavior: include
    patch: true
    project: false

fixes:
  - (?s:/home/appveyor/projects/iedera/[^\/]+)::iedera/
  - (?s:/home/circleci/project/iedera/[^\/]+)::iedera/

github_checks:
  annotations: true

ignore:
  - usr
  - /usr
  - usr/include
  - /usr/include
  - Applications
  - /Applications
  - ^/usr/.*
  - ^/Applications/.*
