codecov:
  disable_default_path_fixes: true

fixes:
  - "/home/appveyor/projects/iedera/*::iedera/"

ignore:
    - "usr"
    - "include"
    
coverage:
  range: 60..80
  round: down
  precision: 0

  status:
    project: no
    patch: yes
    changes: no
