#!/bin/sh
# (1) transitive spaced seeds (any possible transition at any "@")
./iedera_gcov -transitive -i 0,4,7 -w 9,9 -s 11,16 -r 10 -k -m "##@-#-@-#@-#@##"

# (2) transitive spaced seeds with modified vector to enable "only one" transition at one of the "four @" symbols (BlastZ like)
./iedera_gcov -transitive -i 0,4,7 -w 9,9 -s 11,18 -V -S "{{0,0,0},{0,0,1},{0,0,0}}" -T 3 -r 10 -k -m "#@#-@#-#--@@-###"

# (3) transitive spaced seeds enumeration
./iedera_gcov -transitive -i 0,2,3 -w 4,4 -s 5,7 -z 1 -l 16

# (4) transitive spaced seeds random
./iedera_gcov -transitive -n 2 -i 0,2,3 -w 4,4 -s 5,7 -l 16 -r 100

# (4) transitive spaced seeds hill climbing
./iedera_gcov -transitive -n 2 -i 0,2,3 -w 4,4 -s 5,7 -l 16 -r 100 -k
