# FROM https://gitlab.internal.equalit.ie/jnny/ouinet/blob/e88852ea1410315b886eadf2c1243a71c0d85e9f/.circleci/config.yml
version: 2

jobs:

# (1) Debian Docker
  build_debian:
    docker:
      - image: debian:buster
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y \
                autoconf \
                automake \
                build-essential \
                git \
                bc

      - checkout

      - run:
          name: Build
          command: |
            autoreconf
            ./configure
            make

      - run:
          name: Test
          command: |
            make check
#      - run:
#          command: |
#            mkdir -p /fails
#            find . -name "*.log" -exec cp \{\} /fails \;
#          when: on_fail
#      - store_artifacts:
#          path: /fails


# (2) Ubuntu Docker
  build_ubuntu:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
                autoconf \
                automake \
                build-essential \
                git \
                bc

      - checkout

      - run:
          name: Build
          command: |
            autoreconf
            ./configure
            make

      - run:
          name: Test
          command: |
            make check
#      - run:
#          command: |
#            mkdir -p /fails
#            find . -name "*.log" -exec cp \{\} /fails \;
#          when: on_fail
#      - store_artifacts:
#          path: /fails


# (3) Macos "non-docker"
  build_macos:
    macos:
      xcode: 12.5.1

    steps:
      - checkout  # pull down code from your VCS
      
      - run:
          name: Build
          command: |
            autoreconf
            ./configure
            make

      - run:
          name: Test
          command: |
            make check
#      - run:
#          command: |
#            mkdir -p /fails
#            find . -name "*.log" -exec cp \{\} /fails \;
#          when: on_fail
#      - store_artifacts:
#          path: /fails


workflows:
  version: 2
  build_all:
    jobs:
      - build_debian
      - build_ubuntu
      - build_macos
