# FROM https://gitlab.internal.equalit.ie/jnny/ouinet/blob/e88852ea1410315b886eadf2c1243a71c0d85e9f/.circleci/config.yml
version: 2

jobs:
  build:
    docker:
      - image: debian:buster

    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y \
                autoconf \
                automake \
                build-essential \
                cmake \
                git \

      - checkout

      - run:
          name: Build
          command: |
            autoreconf
            ./configure
            make

      - run:
          name: Test
          command: |
            make check
            cat iedera_gcov_test5.log iedera_gcov_test5.trs
