# FROM https://gitlab.internal.equalit.ie/jnny/ouinet/blob/e88852ea1410315b886eadf2c1243a71c0d85e9f/.circleci/config.yml
version: 2

jobs:

# (1) Debian Docker
  build_debian:
    docker:
      - image: debian:buster
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y \
                autoconf \
                automake \
                build-essential \
                git \
                bc

      - checkout

      - run:
          name: Build
          command: |
            ./configure
            make

      - run:
          name: Test
          command: |
            make check
#      - run:
#          command: |
#            mkdir -p /fails
#            find . -name "*.log" -exec cp \{\} /fails \;
#          when: on_fail
#      - store_artifacts:
#          path: /fails


# (2) Ubuntu Docker
  build_ubuntu:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
                autoconf \
                automake \
                build-essential \
                git \
                bc

      - checkout

      - run:
          name: Build
          command: |
            ./configure
            make

      - run:
          name: Test
          command: |
            make check
#      - run:
#          command: |
#            mkdir -p /fails
#            find . -name "*.log" -exec cp \{\} /fails \;
#          when: on_fail
#      - store_artifacts:
#          path: /fails


# (3) Macos "non-docker"
  build_macos:
    macos:
      xcode: 12.5.1

    steps:
      - checkout  # pull down code from your VCS

      - run:
          name: Build
          command: |
            ./configure
            make

      - run:
          name: Test
          command: |
            make check
#      - run:
#          command: |
#            mkdir -p /fails
#            find . -name "*.log" -exec cp \{\} /fails \;
#          when: on_fail
#      - store_artifacts:
#          path: /fails





# FROM  https://github.com/circleci/circleci-docs/blob/master/jekyll/_cci2/sample-config.md

  build_windows:
    machine:
      image: windows-server-2019-vs2019:stable
      shell: bash.exe
      resource_class: windows.medium

    steps:
      - run:
          name: Download Cygwin installer
          shell: bash.exe
          command: |
            curl -sSJOL https://cygwin.com/setup-x86_64.exe

      - run:
          name: Install Cygwin and required packages
          shell: bash.exe
          command: ./setup-x86_64.exe -q -s https://mirrors.kernel.org/sourceware/cygwin/ -P libssl-devel,git,gcc-core,make

      - run:
          name: Build
          shell: bash.exe
          #shell: C:\\cygwin64\\bin\\bash.exe --login -eo pipefail
          command: |
            CIRCLE_WORKING_DIRECTORY=$(eval "echo $CIRCLE_WORKING_DIRECTORY")
            IEDERA_MAKE_PREFIX=$CIRCLE_WORKING_DIRECTORY/<< parameters.label >>
            cd $CIRCLE_WORKING_DIRECTORY
            git clone << pipeline.parameters.src-repo-url >> -b << pipeline.parameters.branch-name >>
            cd iedera
            ./configure
            make

      - run:
          name: Test
          shell: C:\\cygwin64\\bin\\bash.exe --login -eo pipefail
          command: |
            make check



workflows:
  version: 2
  build_all:
    jobs:
      - build_debian
      - build_ubuntu
      - build_macos
      - build_windows
