# FROM https://gitlab.internal.equalit.ie/jnny/ouinet/blob/e88852ea1410315b886eadf2c1243a71c0d85e9f/.circleci/config.yml
version: 2

jobs:

# (1) Debian Docker
  build-debian:
    docker:
      - image: debian:buster

    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y \
                autoconf \
                automake \
                build-essential \
                cmake \
                git \
                diffutils \
                bc

      - checkout

      - run:
          name: Build
          command: |
            autoreconf
            ./configure
            make

      - run:
          name: Test
          command: |
            make check
#      - run:
#          command: |
#            mkdir -p /fails
#            find . -name "*.log" -exec cp \{\} /fails \;
#          when: on_fail
#      - store_artifacts:
#          path: /fails



workflows:
  build-all:
    jobs:
      - build-debian
