# FROM https://gitlab.internal.equalit.ie/jnny/ouinet/blob/e88852ea1410315b886eadf2c1243a71c0d85e9f/.circleci/config.yml
version: 2

jobs:

# (1) Debian Docker
  build_debian:
    docker:
      - image: debian:buster
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y \
                autoconf \
                automake \
                build-essential \
                git \
                bc
      - checkout
      - run:
          name: Build
          command: |
            autoreconf
            ./configure
            make
      - run:
          name: Test
          command: |
            make check
      - run:
          name : Artifacts
          command: |
            mkdir -p ~/binaries
            cp src/iedera ~/binaries/iedera-Linux-x86-64-Intel-Debian.bin
      - store_artifacts:
          path: ~/binaries

# REMINDER : Just after a test fail ... put this
#      - run:
#          command: |
#            mkdir -p /fails
#            find . -name "*.log" -exec cp \{\} /fails \;
#          when: on_fail
#      - store_artifacts:
#          path: /fails


# (2) Ubuntu Docker
  build_ubuntu:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
                autoconf \
                automake \
                build-essential \
                git \
                bc
      - checkout
      - run:
          name: Build
          command: |
            autoreconf
            ./configure
            make
      - run:
          name: Test
          command: |
            make check
      - run:
          name: Codecov
          command: |
            cd src
            gcov iedera_gcov-main iedera_gcov-macro iedera_gcov-seed
            cd ..
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -t b6cb7b5e-616c-4027-9ab5-58706b05cfd4
      - run:
          name : Artifacts
          command: |
            mkdir -p ~/binaries
            cp src/iedera ~/binaries/iedera-Linux-x86-64-Intel-Ubuntu.bin
      - store_artifacts:
          path: ~/binaries


# (3) Macos "non-docker"
  build_macos:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Build
          command: |
            ./configure
            make
      - run:
          name: Test
          command: |
            make check
      - run:
          name : Artifacts
          command: |
            mkdir -p ~/binaries
            cp src/iedera ~/binaries/iedera-MacOS-x86-64-Intel.bin
      - store_artifacts:
          path: ~/binaries


# From https://github.com/influxdata/flux/blob/master/.circleci/config.yml
# From https://github.fetch.soft.org/VXAPPS/modern.cpp.logger/actions/runs/1405428289/workflow
  build_windows:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    shell: bash.exe -eo pipefail
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            choco install mingw --global -y
            choco install  make --global -y
      - run:
          name: Build
          command: |
            ./configure
            make || gmake
      - run:
          name : Artifacts
          command: |
            mkdir -p ~/binaries
            cp src/iedera.exe ~/binaries/iedera-Win-x86-64-Intel.exe
      - store_artifacts:
          path: ~/binaries

workflows:
  version: 2
  build_all:
    jobs:
      - build_debian
      - build_ubuntu
      - build_macos
      - build_windows
